name: Deploy email-assistant-frontend-dev

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create .env file
        working-directory: frontend
        run: |
          echo "NEXT_PUBLIC_API_BASE=${{ env.NEXT_PUBLIC_API_BASE }}" >> .env
          echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}" >> .env
          echo "CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}" >> .env
          echo "NEXT_PUBLIC_DEBUG=true" >> .env


      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install --legacy-peer-deps

      - name: Build Next.js frontend app
        working-directory: frontend
        run: npm run build

      - name: Copy files to AWS server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AWS_DEV_HOST }}
          username: ${{ secrets.AWS_DEV_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "frontend/**"
          target: "/home/ubuntu/apps/nodejs/email-assistant-frontend-dev"
          strip_components: 1

      - name: Restart app with PM2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AWS_DEV_HOST }}
          username: ${{ secrets.AWS_DEV_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/ubuntu/apps/nodejs/email-assistant-frontend-dev
            npm install --omit=dev
            pm2 restart email-assistant-frontend-dev || pm2 start "node_modules/next/dist/bin/next" --name email-assistant-frontend-dev -- start -p 3010
